variable "aws_region" {
  description = "AWS region for Context Firewall."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Name prefix for AWS resources."
  type        = string
  default     = "context-firewall"
}

variable "environment" {
  description = "Deployment environment label."
  type        = string
  default     = "prod"
}

variable "lambda_package_path" {
  description = "Path to a zipped Lambda package generated by scripts/package-lambda.sh."
  type        = string
  default     = "../../build/context-firewall-lambda.zip"
}

variable "auth_required" {
  description = "Require verified Cognito/Okta JWTs at runtime."
  type        = bool
  default     = true
}

variable "jwt_issuer" {
  description = "Optional external Okta/OIDC issuer. Leave empty to use the Cognito user pool created here."
  type        = string
  default     = ""
}

variable "jwt_audience" {
  description = "Optional external OIDC audience. Leave empty to use the Cognito app client id."
  type        = string
  default     = ""
}

variable "jwks_url" {
  description = "Optional JWKS URL. Leave empty to derive it from the issuer."
  type        = string
  default     = ""
}

variable "admin_token" {
  description = "Break-glass admin token for local/admin automation. Prefer JWT security_admin in production."
  type        = string
  sensitive   = true
  default     = "change-me"
}

variable "openai_api_key" {
  description = "Optional OpenAI-compatible API key to store in Secrets Manager."
  type        = string
  sensitive   = true
  default     = ""
}

variable "rate_limit_per_minute" {
  description = "Per-tenant request rate limit."
  type        = number
  default     = 120
}

variable "daily_token_budget_per_tenant" {
  description = "Per-tenant daily estimated token budget."
  type        = number
  default     = 200000
}
